#!/usr/bin/env python3
import json
import os
import urllib.request
import html

USERNAME = os.environ.get("USERNAME", "AnandBinuArjun")
OUT = "security-dashboard.svg"

def get_json(url):
    request = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "github-profile-dashboard"
        },
    )
    with urllib.request.urlopen(request, timeout=20) as response:
        return json.load(response)

def esc(value):
    return html.escape(str(value), quote=True)

user = get_json(f"https://api.github.com/users/{USERNAME}")
repos = []
page = 1

while page <= 10:
    batch = get_json(
        f"https://api.github.com/users/{USERNAME}/repos?per_page=100&page={page}&type=owner"
    )
    if not batch:
        break
    repos.extend(batch)
    if len(batch) < 100:
        break
    page += 1

public_repos = user.get("public_repos", len(repos))
followers = user.get("followers", 0)
following = user.get("following", 0)

top = sorted(
    repos,
    key=lambda item: (
        item.get("stargazers_count", 0),
        item.get("forks_count", 0),
    ),
    reverse=True,
)[:5]

top_star = top[0].get("stargazers_count", 0) if top else 0
max_star = max([item.get("stargazers_count", 0) for item in top] + [1])

name_map = {
    "SENTINEL-IOT": "SENTINEL-IoT",
    "threat-intelligence-cti-analysis": "CTI Analysis",
    "AI-Powered-Personal-Digital-Safety-Assistant": "AI Digital Safety",
    "TOTAL-ENTITY": "TOTAL ENTITY",
    "TOTAL-ENTITY-Exposure-Monitor": "TOTAL ENTITY",
}

def display_name(name):
    return name_map.get(name, name[:20])

bar_y = [306, 344, 382, 420, 458]
bar_colors = ["#34d399", "#8b5cf6", "#8b5cf6", "#22d3ee", "#22d3ee"]
project_rows = []

for item, y, color in zip(top, bar_y, bar_colors):
    stars = item.get("stargazers_count", 0)
    width = max(8, int(350 * stars / max_star))
    project_rows.append(
        f'<text x="372" y="{y}" fill="#94a3b8">{esc(display_name(item.get("name", "repo")))}</text>'
        f'<rect x="500" y="{y-12}" width="350" height="16" rx="8" fill="#171e2d"/>'
        f'<rect x="500" y="{y-12}" width="{width}" height="16" rx="8" fill="{color}"/>'
        f'<text x="865" y="{y}" fill="#e2e8f0">{stars}</text>'
    )

project_rows = "".join(project_rows)

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="610" viewBox="0 0 1200 610">
<title>Anand Binu Arjun — Developer Dashboard</title>
<desc>Live GitHub profile dashboard generated by GitHub Actions.</desc>
<rect width="1200" height="610" rx="28" fill="#05070b"/>
<rect x="1" y="1" width="1198" height="608" rx="27" fill="none" stroke="#22d3ee" stroke-opacity=".55"/>
<g font-family="monospace">
<text x="52" y="50" fill="#a78bfa" font-size="12" letter-spacing="2">// DEVELOPER DASHBOARD</text>
<text x="52" y="84" fill="#f8fafc" font-family="Arial, sans-serif" font-size="29" font-weight="700">Profile at a glance</text>
<rect x="1002" y="38" width="142" height="26" rx="13" fill="#071b17" stroke="#34d399" stroke-opacity=".5"/>
<circle cx="1018" cy="51" r="4" fill="#34d399"/>
<text x="1030" y="55" fill="#34d399" font-size="9" letter-spacing="1">LIVE · GITHUB</text>
</g>

<rect x="45" y="112" width="275" height="430" rx="22" fill="#0a101a" stroke="#22d3ee" stroke-opacity=".5"/>
<rect x="62" y="130" width="241" height="38" rx="10" fill="#08131d" stroke="#1e293b"/>
<text x="78" y="153" fill="#22d3ee" font-family="monospace" font-size="10" letter-spacing="1.5">DEVELOPER ID</text>
<text x="255" y="153" text-anchor="end" fill="#64748b" font-family="monospace" font-size="9">LIVE</text>
<rect x="78" y="187" width="209" height="135" rx="18" fill="#0f172a" stroke="#8b5cf6" stroke-opacity=".65"/>
<circle cx="182" cy="252" r="53" fill="#111827" stroke="#22d3ee" stroke-opacity=".65"/>
<circle cx="182" cy="252" r="40" fill="#0b1220" stroke="#34d399" stroke-opacity=".35"/>
<text x="182" y="243" text-anchor="middle" fill="#22d3ee" font-family="Arial, sans-serif" font-size="26" font-weight="800">AA</text>
<text x="182" y="267" text-anchor="middle" fill="#94a3b8" font-family="monospace" font-size="8">SECURITY ENGINEER</text>
<text x="78" y="350" fill="#f8fafc" font-family="Arial, sans-serif" font-size="21" font-weight="800">ANAND BINU ARJUN</text>
<text x="78" y="373" fill="#22d3ee" font-family="monospace" font-size="10">CYBERSECURITY · AI · IoT</text>
<line x1="78" y1="392" x2="287" y2="392" stroke="#1e293b"/>
<text x="78" y="418" fill="#64748b" font-family="monospace" font-size="9">BASE</text>
<text x="78" y="438" fill="#e2e8f0" font-family="monospace" font-size="11">UNITED KINGDOM</text>
<text x="190" y="418" fill="#64748b" font-family="monospace" font-size="9">FOCUS</text>
<text x="190" y="438" fill="#e2e8f0" font-family="monospace" font-size="11">SECURITY SYSTEMS</text>
<text x="78" y="474" fill="#64748b" font-family="monospace" font-size="9">CURRENT MODE</text>
<text x="78" y="495" fill="#34d399" font-family="monospace" font-size="11">BUILD · RESEARCH · SHIP</text>
<rect x="78" y="510" width="209" height="2" fill="#1e293b"/>
<rect x="78" y="510" width="136" height="2" fill="#22d3ee"/>

<g font-family="monospace">
<rect x="345" y="112" width="185" height="82" rx="15" fill="#0d1220" stroke="#334155"/>
<rect x="363" y="128" width="18" height="3" rx="1" fill="#22d3ee"/>
<text x="363" y="153" fill="#64748b" font-size="9">PUBLIC REPOS</text>
<text x="363" y="181" fill="#f8fafc" font-size="26" font-family="Arial" font-weight="800">{esc(public_repos)}</text>

<rect x="548" y="112" width="185" height="82" rx="15" fill="#0d1220" stroke="#334155"/>
<rect x="566" y="128" width="18" height="3" rx="1" fill="#fbbf24"/>
<text x="566" y="153" fill="#64748b" font-size="9">TOP PROJECT</text>
<text x="566" y="181" fill="#f8fafc" font-size="26" font-family="Arial" font-weight="800">{esc(top_star)}★</text>

<rect x="751" y="112" width="185" height="82" rx="15" fill="#0d1220" stroke="#334155"/>
<rect x="769" y="128" width="18" height="3" rx="1" fill="#a78bfa"/>
<text x="769" y="153" fill="#64748b" font-size="9">FOLLOWERS</text>
<text x="769" y="181" fill="#f8fafc" font-size="26" font-family="Arial" font-weight="800">{esc(followers)}</text>

<rect x="954" y="112" width="190" height="82" rx="15" fill="#0d1220" stroke="#334155"/>
<rect x="972" y="128" width="18" height="3" rx="1" fill="#f472b6"/>
<text x="972" y="153" fill="#64748b" font-size="9">FOLLOWING</text>
<text x="972" y="181" fill="#f8fafc" font-size="26" font-family="Arial" font-weight="800">{esc(following)}</text>
</g>

<rect x="345" y="214" width="590" height="282" rx="18" fill="#0a101a" stroke="#334155"/>
<text x="372" y="246" fill="#f8fafc" font-family="Arial, sans-serif" font-size="18" font-weight="700">MOST-STARRED PROJECTS</text>
<text x="372" y="267" fill="#64748b" font-family="monospace" font-size="9">PUBLIC REPOSITORIES · CURRENT GITHUB SNAPSHOT</text>
<g font-family="monospace" font-size="10">{project_rows}</g>

<rect x="955" y="214" width="189" height="132" rx="18" fill="#0a101a" stroke="#334155"/>
<text x="976" y="240" fill="#f472b6" font-family="monospace" font-size="10">COMMUNITY</text>
<text x="976" y="275" fill="#f8fafc" font-family="Arial" font-size="23" font-weight="800">{esc(followers)}</text>
<text x="976" y="292" fill="#64748b" font-family="monospace" font-size="8">FOLLOWERS</text>
<text x="1050" y="275" fill="#f8fafc" font-family="Arial" font-size="23" font-weight="800">{esc(following)}</text>
<text x="1050" y="292" fill="#64748b" font-family="monospace" font-size="8">FOLLOWING</text>
<text x="976" y="320" fill="#94a3b8" font-family="monospace" font-size="8">@{esc(USERNAME)}</text>

<rect x="955" y="364" width="189" height="132" rx="18" fill="#0a101a" stroke="#334155"/>
<circle cx="976" cy="389" r="4" fill="#34d399"/>
<text x="988" y="393" fill="#34d399" font-family="monospace" font-size="9">BUILDING</text>
<text x="976" y="420" fill="#e2e8f0" font-family="monospace" font-size="9">SHIELDDESK</text>
<text x="976" y="438" fill="#94a3b8" font-family="monospace" font-size="8">AI-assisted SOC</text>
<text x="976" y="462" fill="#e2e8f0" font-family="monospace" font-size="9">SENTINEL-IoT</text>
<text x="976" y="480" fill="#94a3b8" font-family="monospace" font-size="8">IoT threat intelligence</text>
</svg>
'''

with open(OUT, "w", encoding="utf-8") as file:
    file.write(svg)

print(f"Generated {OUT}: {public_repos} repos, {followers} followers, {following} following, top project {top_star} stars.")
